# Generated by Django 3.1.7 on 2021-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=100)),
                ('rank', models.IntegerField(unique=True)),
            ],
        ),
    ]
