# Generated by Django 3.1.7 on 2021-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=100)),
            ],
        ),
    ]
