# Generated by Django 3.1.7 on 2021-04-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=100),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=100)),
                ('label', models.CharField(choices=[('new', 'new'), ('hot', 'hot'), ('most_viewed', 'most_viewed'), ('', 'default')], max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('specification', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
