# Generated by Django 3.1.7 on 2021-04-16 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210416_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=200)),
                ('slug', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=100)),
                ('review', models.TextField(blank=True)),
            ],
        ),
    ]
