# Generated by Django 3.1.7 on 2021-04-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210424_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('', 'defult')], default='active', max_length=50, null=True),
        ),
    ]
