# Generated by Django 3.1.7 on 2021-04-28 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutcart',
            name='date_checked',
        ),
        migrations.RemoveField(
            model_name='checkoutcart',
            name='items',
        ),
        migrations.AddField(
            model_name='carttotal',
            name='date_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
